quarkus.application.name=fiapx-videos
quarkus.swagger-ui.always-include=true
quarkus.datasource.db-kind=postgresql

%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# Porta distinta por servico para rodar os tres em dev local.
%dev.quarkus.http.port=8080
